import "./item1.jpeg";
const menu = [
  {
    id: 1,
    title: "Coffee",
    category: "Coffee & Tea",
    price: 15.99,
    img: "./images/item1.jpeg",
    desc: `A plain black cup of coffee has 2.4 calories per serving, which comes from a minimal amount of protein.`,
  },
  {
    id: 2,
    title: "Fresh Lemon Juice",
    category: "Soft Drinks",
    price: 13.99,
    img: "./images/item2.jpeg",
    desc: `Lemon juice is a rich source of vitamin C with only three calories per tablespoon and minimal amounts of sugar. `,
  },
  {
    id: 3,
    title: "Chocobar",
    category: "Ice Creams",
    price: 6.99,
    img: "./images/item3.jpeg",
    desc: `There are 329 calories in serving of Chocobar by Amul from: Carbs 24g, Fat 24g, Protein 4g. Get full nutrition facts for your favorite foods and brands`,
  },
  {
    id: 4,
    title: "Black Coffee",
    category: "Coffee & Tea",
    price: 20.99,
    img: "./images/item4.JPG",
    desc: `Black coffee helps in rapid weight loss by making you work out more if you have it 30 minutes before you hit the gym. Black coffee helps to boost metabolism by approximately 50 percent. `,
  },
  {
    id: 5,
    title: "Pine Apple Juice",
    category: "Soft Drinks",
    price: 22.99,
    img: "./images/item5.jpeg",
    desc: `Pineapple juice contains an enzyme called bromelain. This enzyme is found in the juice of pineapple and helps in metabolising protein, which in turn helps burn away the excess belly fat. `,
  },
  {
    id: 6,
    title: "Amul Cassata",
    category: "Ice Creams",
    price: 18.99,
    img: "./images/item6.jpeg",
    desc: `There are 221 calories in serving of Cassata Slice Icecream by Havmor from: Carbs 26g, Fat 11g, Protein 4g. `,
  },
  {
    id: 7,
    title: "Masala Tea",
    category: "Coffee & Tea",
    price: 8.99,
    img: "./images/item7.jpeg",
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: "Mosambi",
    category: "Soft Drinks",
    price: 12.99,
    img: "./images/item8.jpeg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: "Cupice",
    category: "Ice Creams",
    price: 16.99,
    img: "./images/item9.jpeg",
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
